# Generated by Django 4.2.9 on 2024-06-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesagoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time', models.DateTimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-time'],
            },
        ),
    ]
