# Generated by Django 4.2.9 on 2024-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0002_mesagoj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesagoj',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
