# Generated by Django 4.2.9 on 2024-06-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0003_alter_mesagoj_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vidbendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
