# Generated by Django 4.2.9 on 2024-06-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0004_vidbendo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vidbendo',
        ),
    ]
