# Generated by Django 4.2.9 on 2024-06-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0006_vidbendo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vidbendo',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveField(
            model_name='vidbendo',
            name='time',
        ),
    ]
