# Generated by Django 4.2.9 on 2024-06-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0007_alter_vidbendo_options_remove_vidbendo_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vidbendo',
            options={'ordering': ['-time'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='vidbendo',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='vidbendo',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='source_video/'),
        ),
    ]
