# Generated by Django 4.2.9 on 2024-06-06 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0008_alter_vidbendo_options_vidbendo_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidbendo',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='source_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
