# Generated by Django 5.0.6 on 2024-06-07 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0011_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='aplico/static/source_foto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
