# Generated by Django 5.0.6 on 2024-06-07 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0012_alter_foto_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='apliko/static/source_foto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
