# Generated by Django 5.0.6 on 2024-06-08 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0015_foto_name_alter_foto_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidbendo',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='vidbendo',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='apliko/static/source_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
