# Generated by Django 5.0.6 on 2024-06-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0016_vidbendo_name_alter_vidbendo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='labels',
            field=models.TextField(blank=True, null=True, verbose_name='Метки'),
        ),
    ]
