# Generated by Django 5.0.6 on 2024-06-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0017_foto_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='name_txt',
            field=models.TextField(blank=True, null=True, verbose_name='Путь txt'),
        ),
    ]
