# Generated by Django 5.0.6 on 2024-06-11 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0018_foto_name_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arkivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='apliko/static/source_arkivo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архивы',
                'ordering': ['-time'],
            },
        ),
    ]
