# Generated by Django 5.0.6 on 2024-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0019_arkivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arkivo',
            name='name_arch',
            field=models.TextField(blank=True, null=True, verbose_name='Путь к архиву'),
        ),
        migrations.AddField(
            model_name='arkivo',
            name='name_arch_lbls',
            field=models.TextField(blank=True, null=True, verbose_name='Путь к меткам'),
        ),
    ]
