# Generated by Django 5.0.6 on 2024-06-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0020_arkivo_name_arch_arkivo_name_arch_lbls'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidbendo',
            name='in_process',
            field=models.TextField(default='False', verbose_name='В обработке'),
        ),
    ]
