# Generated by Django 5.0.6 on 2024-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0021_vidbendo_in_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidbendo',
            name='in_process',
            field=models.TextField(blank=True, null=True, verbose_name='В обработке'),
        ),
    ]
