# Generated by Django 5.0.6 on 2024-06-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0022_alter_vidbendo_in_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidbendo',
            name='st256',
            field=models.TextField(blank=True, null=True, verbose_name='Таймлайн'),
        ),
    ]
