# Generated by Django 5.0.6 on 2024-06-13 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0023_vidbendo_st256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkivo',
            name='upload',
            field=models.FileField(default='', upload_to='apliko/static/source_arkivo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='foto',
            name='upload',
            field=models.FileField(default='', upload_to='apliko/static/source_foto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='vidbendo',
            name='upload',
            field=models.FileField(default='', upload_to='apliko/static/source_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
