# Generated by Django 5.0.6 on 2024-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0025_alter_arkivo_upload_alter_foto_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesagoj',
            name='is_new',
            field=models.TextField(default='False', verbose_name='Актуальность'),
        ),
    ]
