# Generated by Django 5.0.6 on 2024-06-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0026_mesagoj_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesagoj',
            name='is_new',
        ),
        migrations.AddField(
            model_name='mesagoj',
            name='is_new2',
            field=models.TextField(null=True, verbose_name='Актуальность'),
        ),
    ]
