# Generated by Django 5.0.6 on 2024-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliko', '0027_remove_mesagoj_is_new_mesagoj_is_new2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesagoj',
            name='is_new2',
        ),
        migrations.AddField(
            model_name='mesagoj',
            name='is_new3',
            field=models.TextField(default='False', null=True, verbose_name='Актуальность'),
        ),
    ]
